tasks:
  - name: Setup
    init: corepack enable && pnpm install && pnpm build
    command: pnpm dev

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - redhat.vscode-yaml
