{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authensor.fullname" . }}
  labels:
    {{- include "authensor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.databaseUrl }}
  DATABASE_URL: {{ .Values.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.bootstrapAdminToken }}
  AUTHENSOR_BOOTSTRAP_ADMIN_TOKEN: {{ .Values.bootstrapAdminToken | quote }}
  {{- end }}
{{- end }}
